### ISSUE TITLE
Upgrade from 0.5 to 1.1

### ISSUE THREAD

**Issue by SNDdeNarchives** [WeAreAVP/fixity#31]
Please bear with me, I am new to Fixity.  One of my first tasks was to upgrade our organization's Fixity 0.5 to the new release.  The organization has been using 0.5 for several years, so there are a number of "projects", as well as the "reports" and "history" folders" from 0.5 that need to be imported (is that the right word) into 1.1, but it didn't happen automatically.  Any help you could offer would be greatly appreciated.

**Comment by pvizner** [comment]
Hi,
Currently projects are not automatically migrated to newer versions of Fixity so you would have to do that manually for each project. Please check the "Import Project" section of our [Fixity User Guide](https://www.weareavp.com/wp-content/uploads/2018/05/Fixity_UserGuide.pdf) for details on how to do this.
If you have any further questions let me know. You can also join the [Fixity google group.](https://groups.google.com/d/forum/fixity-users)
Best,
Pamela

**Comment by SNDdeNarchives** [comment]
Thanks Pamela!
